### ISSUE TITLE
Min/max counting duplicates

### ISSUE THREAD

**Issue by jungle-boogie** [chrisbra/csv.vim#67]
Hello,

With this sample data:
http://www.sharecsv.com/s/9096d32f98aa0ac671a1cca16fa43be8/SalesJan2009.csv

It looks like :Max counts 7500 all ten times. I thought this would be like :Count distinct where it counts the value once and moves along to next max value.

This is also occurring for :Min:
`[0.0, 250.0, 800.0, 1200.0, 1200.0, 1200.0, 1200.0, 1200.0, 1200.0, 1200.0]`

Thanks!

**Comment by chrisbra** [comment]
Hi jungle-boogie!

On Mo, 17 Aug 2015, jungle-boogie wrote:

> Hello,
> 
> With this sample data:
> http://www.sharecsv.com/s/9096d32f98aa0ac671a1cca16fa43be8/SalesJan2009.csv
> 
> It looks like :Max counts 7500 all ten times. I thought this would be like :Count distinct where it counts the value once and moves along to next max value.
> 
> This is also occurring for :Min:
> `[0.0, 250.0, 800.0, 1200.0, 1200.0, 1200.0, 1200.0, 1200.0, 1200.0, 1200.0]`
> 
> Thanks!

Should work now. Thanks for reporting!

Best,
Christian
-- 
Nur wer alt wird, erhält eine vollständige und angemessene Vorstellung 
vom Leben.
		-- Arthur Schopenhauer

**Comment by jungle-boogie** [comment]
Hi,

> Should work now. Thanks for reporting!

I pulled new changes and I have e6fa0b855c67fdc621f42ca724fd85e12ee3db4f but using the sales file, I still see this:

`[13000.0, 7500.0, 7500.0, 7500.0, 7500.0, 7500.0, 7500.0, 7500.0, 7500.0, 7500.0]`

`1200` value is repeated 8 times.

Do you think this is a problem with the CSV file?

Thanks!

**Comment by chrisbra** [comment]
Hi jungle-boogie!

On Mi, 19 Aug 2015, jungle-boogie wrote:

> Hi,
> 
> > Should work now. Thanks for reporting!
> 
> I pulled new changes and I have e6fa0b855c67fdc621f42ca724fd85e12ee3db4f but using the sales file, I still see this:
> 
> `[13000.0, 7500.0, 7500.0, 7500.0, 7500.0, 7500.0, 7500.0, 7500.0, 7500.0, 7500.0]`
> 
> `1200` value is repeated 8 times.
> 
> Do you think this is a problem with the CSV file?

Use the distinct keyword, e.g. :MaxCol distinct

Best,
Christian
-- 
Wie man sein Kind nicht nennen sollte: 
  Knut Schfleck

**Comment by jungle-boogie** [comment]
Hello Chrisbra,

> Use the distinct keyword, e.g. :MaxCol distinct

Now that works perfectly!

Thanks a million for your plug-in.

Best,
sean
