### ISSUE TITLE
CSV: Error: getting Column numbers, aborting

### ISSUE THREAD

**Issue by joelostblom** [chrisbra/csv.vim#72]
Hi it's me again,
Thanks for fixing #71 so quickly. I tried the updated version of csv-vim just now, but I am receiving the error `CSV: Error: getting Column numbers, aborting` when trying to open csv files now.

I previously had version 0.31 installed from the homepage. I uninstalled it by doing `:RmVimball csv.vmb` and then installed by cloning the git repo, opening `csv.vmb` and running `:so %`.  also tried installing by running `make` in the downloaded git-directory, which gives the same result. When I uninstall the updated plugin from Github and install the old version 0.31 again,  opening csv-files works fine.

Any idea of what the issue is?

**Comment by chrisbra** [comment]
Are you using a plugin manager? I think, you should not mix using vimball and plugin manager.  I just updated the vimball version. Please try that.
What i did for testing: I used your testfile:

    # This file contains this and that
    # Some more comments

    Col1,Col2,Col3
    row1,row1,row1,
    row2,row2,row2

Then I added some empty lines at the top and restarted vim. This correctly adapted the highlighting. Can you try this?

**Comment by joelostblom** [comment]
Sorry for the late reply, I got busy at work. I am using VimPlug for a few other plugins, but that never caused any conflicts with VimBall back when I was using csv.vim-0.31, so I don't think that is the culprit.

I tried reinstalling the updated vimball, but I am getting the same error as before. I have been able to pinpoint it to `ArrangeColumn`. I have this set up automatically in my `.vimrc` so I forgot about it earlier. When I commented it out, everything works as expected and the correct line is highlighted as the header line when opening the testfile.

When I try to run `ArrangeColumn` with the testfile from inside vim, the same buggy behavior repeats itself, so it seems like that function is not playing well with the edits you made regarding #71 .


 More info regarding the error:
- In addition to the error message, the processor spins up, vim freezes for about  10 seconds and then renders the file with the columns in incorrect positions, some lines folded, and

**Comment by chrisbra** [comment]
Hi joelostblom!

On So, 29 Nov 2015, joelostblom wrote:

> Sorry for the late reply, I got busy at work. I am using VimPlug for a few other plugins, but that never caused any conflicts with VimBall back when I was using csv.vim-0.31, so I don't think that is the culprit.
> 
> I tried reinstalling the updated vimball, but I am getting the same error as before. I have been able to pinpoint it to `ArrangeColumn`. I have this set up automatically in my `.vimrc` so I forgot about it earlier. When I commented it out, everything works as expected and the correct line is highlighted as the header line when opening the testfile.
> 
> When I try to run `ArrangeColumn` with the testfile from inside vim, the same buggy behavior repeats itself, so it seems like that function is not playing well with the edits you made regarding #71 .
> 
> 
>  More info regarding the error:
> - In addition to the error message, the processor spins up, vim freezes for about  10 seconds and then renders the file with the columns in incorrect positions, some lines folded, and 

Thanks for pointing it out. I'll look into fixing this next week.

Best,
Christian
-- 
Ich hatte gehofft, daß das durch je höher der Kirchturm desto
bim aufgefangen wird.  *lautdenk*
		-- banshee auf #LinuxGER

**Comment by chrisbra** [comment]
please check again with the latest commit. I fixed an issue with `:ArrangeCol` command.

**Comment by joelostblom** [comment]
Thanks for the update, unfortunately it does not seem to fix the problem for me.

To illustrate the problem, when opening the a csv-file without any automatic arrangement of columns, the comments and the header line are identified correctly and everything looks like expected:
![image](https://cloud.githubusercontent.com/assets/4560057/11522072/29856144-9881-11e5-892a-0f2e0ba1ede9.png)

After `:ArrangeColumn`, vim freezes for ten seconds and then renders the columns disorganized and spits out the same error message as earlier:
![image](https://cloud.githubusercontent.com/assets/4560057/11522110/b192cfea-9881-11e5-92e9-9617ad4b3c51.png)

**Comment by chrisbra** [comment]
Okay, I think I found the problem. It is not obvious, because the `:ArrangeColumn` command behaves correctly. If you want to rearrange the complete file, please use `:%ArrangeColumn`. I have added some more sanitizer checks, that it does not try to arrange the header comments or the empty lines. That should work now. Please test again.

**Comment by joelostblom** [comment]
Ok, sorry for the command confusion. `:ArrangeColumn` was initially giving me the same result as `let g:csv_autocmd_arrange = 1` in my `.vimrc`, so I thought they were the same command. I also apologize for all the extra work this has created...

With the new version, there are a few different issues that occurs after running `:%ArrangeColumn` or setting `let g:csv_autocmd_arrange = 1` in `.vimrc`:

## csv-files starting with a comment followed by either the header line or a blank line and then the header line.

#### `:%ArrangeColumn`
The warning message is displayed, but vim does not freeze and the columns are nicely arranged. With the old version, this exact behavior occurred when all rows did not have the same number of columns.

#### `let g:csv_autocmd_arrange = 1`
The warning message is displayed, but vim does not freeze and the columns are nicely arranged.

## csv-files starting with the header line 

#### `:%ArrangeColumn`
I now receive a new error:
![image](https://cloud.githubusercontent.com/assets/4560057/11532432/bc63d202-98d1-11e5-9183-c034077d94df.png)
Vim then arranges the columns correctly and there is no freezing.

#### `let g:csv_autocmd_arrange = 1`
![image](https://cloud.githubusercontent.com/assets/4560057/11532369/6b08e474-98d1-11e5-95dc-c05cfb00d75a.png)
The files opens but the columns are not arranged. When I try `%ArrangeColumns`, the above error message shows up again and the columns do not arrange.

## csv-files starting with a blank line followed by the header line
Everything works as expected.

**Comment by chrisbra** [comment]
On Mi, 02 Dez 2015, joelostblom wrote:

> Ok, sorry for the command confusion. `:ArrangeColumn` was initially giving me the same result as `let g:csv_autocmd_arrange = 1` in my `.vimrc`, so I thought they were the same command. I also apologize for all the extra work this has created...
> 
> With the new version, there are a few different issues that occurs after running `:%ArrangeColumn` or setting `let g:csv_autocmd_arrange = 1` in `.vimrc`:
> 
> ## csv-files starting with a comment followed by either the header line or a blank line and then the header line.
> 
> #### `:%ArrangeColumn`
> The warning message is displayed, but vim does not freeze and the columns are nicely arranged. With the old version, this exact behavior occurred when all rows did not have the same number of columns.
> 
> #### `let g:csv_autocmd_arrange = 1`
> The warning message is displayed, but vim does not freeze and the columns are nicely arranged.
> 
> ## csv-files starting with the header line 
> 
> #### `:%ArrangeColumn`
> I now receive a new error:
> ![image](https://cloud.githubusercontent.com/assets/4560057/11532432/bc63d202-98d1-11e5-9183-c034077d94df.png)
> Vim then arranges the columns correctly and there is no freezing.
> 
> #### `let g:csv_autocmd_arrange = 1`
> ![image](https://cloud.githubusercontent.com/assets/4560057/11532369/6b08e474-98d1-11e5-95dc-c05cfb00d75a.png)
> The files opens but the columns are not arranged. When I try `%ArrangeColumns`, the above error message shows up again and the columns do not arrange.
> 
> ## csv-files starting with a blank line followed by the header line
> Everything works as expected.

Okay, this is getting ridiculous and i apologize for introducing new 
errors.

I think the problem was, that the b:csv_headerline was not always 
defined, so I made some more changes to make sure that variable is only 
used when it also exists.

Best,
Christian
-- 
Geht die Bäurin in die Breite, sucht der Bauer schnell das Weite.

**Comment by joelostblom** [comment]
I just tested the newest version, but I am still receiving the same error patterns as described in my last post.

**Comment by joelostblom** [comment]
I think the culprit for the persistent `b:csv_headerline` errors is line 720. In addition to your added check for if the variable exists, I split that if-expression into a nested expression and it seems to help.

I am still getting the warning message `CSV: Error: getting Column numbers, aborting!`, but vim nicely arrange the columns.

**Comment by joelostblom** [comment]
I believe I just created a pull request... Not sure if I did it correctly, first time, haha. Please check it out so I don't mess things up =)

**Comment by joelostblom** [comment]
So the only remaining minor annoyance is that I am getting the column number error message every time I try to arrange columns in a file starting with a comment (or opening a file if autoarrange is set in .vimrc).

I was looking at the `MaxColumns`-function at line 524 that throws the error, but I couldn't really figure out what to do. Maybe replace `"a:1"` with `"a:" . b:csv_headerline` somewhere? But you already filter out comments so I couldn't figure out exactly what to do...

**Comment by chrisbra** [comment]
okay, I have a suspicion. Please use latest version and do `:set verbose=1`. Then run the `:%ArrangeCol` command as before. After it finished with the error, use `:mes` command and look at the line 

     ArrangeCol Start: 8, End: 10

That should start at the first line or your data and end at the last line. I suspect it starts before (e.g. where the comment is) and it obviously can't calculate the optimal column width for that line, therefore it complains.

**Comment by joelostblom** [comment]
I installed the new version and set the verbose variable inside vim with the test-file open. However, this is all the output after using `:mes`.
![image](https://cloud.githubusercontent.com/assets/4560057/11572703/a0a45a8c-99d0-11e5-9a32-50445d9b57dc.png)

**Comment by chrisbra** [comment]
okay i moved it a little higher. Please try again.

**Comment by joelostblom** [comment]
I am getting the same output from `:mes` as previously. Are you seeing something different on your system?

**Comment by chrisbra** [comment]
Sorry can't reproduce it currently. Have you configured the plugin and set some variables?

**Comment by joelostblom** [comment]
Sorry, I don't understand. Which plugin should I configure (mes or csv.vim) and how? And what variables should I set (I set `verbose=1` as per your post above)?

**Comment by joelostblom** [comment]
Ok, here we go. I missed that I needed to make the .vmb-file myself every time, I was using the prepackaged one from Dec 3rd. With the latest version (pulled just now), I am still getting the column number error message. Step by step:

Opening the file without autoarrange in .vimrc, the comment line is now highlighted as the header line instead of in grey for comments:
![image](https://cloud.githubusercontent.com/assets/4560057/11635048/35e46b32-9ce2-11e5-8470-98e2d938c555.png)

However, after `:set verbose=1` and `:%ArrangeColumn`, the correct region is specified (line 3-5) and columns are arranged, but the error message is still displayed (`:mes` shows the same output).
![image](https://cloud.githubusercontent.com/assets/4560057/11635081/71dc1856-9ce2-11e5-9437-fe8109a8daed.png)

If I type `:%ArrangeColumn` a second time, there is no error message and columns stay arranged. Interestingly, if I append a line to the file before arranging the columns, the error message is not displayed! The start position is still 3, but the end position is now 6. The comment is still highlighted as a header line.

![image](https://cloud.githubusercontent.com/assets/4560057/11635189/100a4836-9ce3-11e5-8f4b-81075556ebc3.png)

**Comment by jungle-boogie** [comment]
Hi @joelostblom,

I have a .vim directory in ~/ and in that I have a bundle. In the bundle directory (~/.vim/bundle), I have csv.vim. I simply` git clone https://github.com/chrisbra/csv.vim` in the bundle directory and when an update is ready, `git pull`. 

You could download the zip from master and move into your bundle directory, but when I download it, I need to change the name from `csv.vim-master` to `csv.vim`.

**Comment by joelostblom** [comment]
Thanks for the suggestion. In this case, the latest update to `csv.vmb` on master was 6 days ago, but there has been updates to some of the scripts ~ 2 days ago. So if I git pull the entire directory and make the `csv.vmb` myself, wouldn't I be more up to date than with your approach? Your might be more convenient though as soon as we have figured out the issues I am having.

**Comment by jungle-boogie** [comment]
I think in the end mine is more straight forward as you just `git pull` from a single directory.

As far as resolving your issue, have you shared the exact file that has a problem? You can use gist.github.com to share it.

**Comment by joelostblom** [comment]
Yeah, the source file is shared above. It is quite simple, just:

```
# This file contains this and that
# Some more comments

Col1,Col2,Col3
row1,row1,row1,
row2,row2,row2
```

In the latest test I did, I only have one commented line. But I don't think it is the specific file as I am having the same issue with all my csv-files.

**Comment by chrisbra** [comment]
Hi joelostblom!

On Di, 08 Dez 2015, joelostblom wrote:

> Yeah, the source file is shared above. It is quite simple, just:
> 
> ```
> # This file contains this and that
> # Some more comments
> 
> Col1,Col2,Col3
> row1,row1,row1,
> row2,row2,row2
> ```
> 
> In the latest test I did, I only have one commented line. But I don't think it is the specific file as I am having the same issue with all my csv-files.

I think I found the error. Please update and test again. Thanks for 
being so patient.

Best,
Christian
-- 
Bürokommunikation? Schreibtischgelaber!

**Comment by joelostblom** [comment]
You did find the error! There are now no warning messages and the columns arrange correctly. Thanks for spending so much time on it!

I noticed that the comment lines are now highlighted as header lines rather than comments. I can open a new issue if you want, but I imagined it was just a small fix since everything else is working now. Thanks again!

Currently:
![image](https://cloud.githubusercontent.com/assets/4560057/11674375/52dac990-9dee-11e5-83cc-c4b2cc7f2005.png)

Previously:
![image](https://cloud.githubusercontent.com/assets/4560057/11674349/1a4f5b18-9dee-11e5-9c5e-631472d8f9af.png)

**Comment by chrisbra** [comment]
Hi joelostblom!

On Di, 08 Dez 2015, joelostblom wrote:

> You did find the error! There are now no warning messages and the columns arrange correctly. Thanks for spending so much time on it!
> 
> I noticed that the comment lines are now highlighted as header lines rather than comments. I can open a new issue if you want, but I imagined it was just a small fix since everything else is working now. Thanks again!

Can you show me the output of `:syn`

Best,
Christian
-- 
Er lobt mit Vergnügen die Tugenden des andern und rügt mit Vergnügen
seine Fehler.
		-- Jean Paul (eig. Johann Paul Friedrich Richter)

**Comment by joelostblom** [comment]
![image](https://cloud.githubusercontent.com/assets/4560057/11686600/c26c73ce-9e4f-11e5-9948-790b347f23b6.png)

**Comment by chrisbra** [comment]
Please set `:let g:csv_comment='#'` in your .vimrc, the default comes from the commentstring setting and is `/*%s*/` and therefore the plugins expects `/*` as comment string by default

**Comment by joelostblom** [comment]
I already have that line in my .vimrc. Overall my .vimrc is the same as
when the comments were highlighted correctly in the screenshot above, the
only thing that changed are the new updates to csv.vmb.

I think comments are detected correctly, just highlighted incorrectly. I
did a test where I switched # to /* and now only the first comment is in
bold red, instead of both the comments and the first following line as
shown previously.
​

**Comment by chrisbra** [comment]
Are you sure, that is correct in your .vimrc? The syntax file should pick it up and I don't see, why it shouldn't. Can you show me the vimrc?

**Comment by joelostblom** [comment]
Yes I'm pretty sure it is correct. Here is a minimal version of my .vimc,
which I tested with and it reproduced the highlighting problem:

```
call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'ervandew/supertab'
Plug 'morhetz/gruvbox'
call plug#end()

" Set colorscheme
colorscheme gruvbox
set background=dark

" Enable pandoc spellcheck
let g:pandoc#spell#enabled = 1

" Enable recognition of file types >> syntax highlighting (required for
csv-plugin)
:filetype plugin indent on

" Calculate and auto arange column width in csv-files under a certain size
let g:csv_autocmd_arrange = 1
let g:csv_autocmd_arrange_size = 2048*2048

" Enable comments in csv files, this plugin is genious!
:let g:csv_comment = '#'

" Set the default vim clipboard to be the same as the system clipboard
set clipboard=unnamedplus

" Remap command key not to have to press shift
nore ; :
```

**Comment by chrisbra** [comment]
and you installed the csv plugin as vimball, right?

**Comment by joelostblom** [comment]
Joy! I just pulled the newest `csv.vmb` changes from 20 h ago and comments are highlighted correctly now!

Again, thank you so much for creating this plugin and being so responsive in sorting out the issues I was having =)
